services:
  - type: web
    name: volleyboll
    env: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: VAPID_PUBLIC_KEY
        value: ""
      - key: VAPID_PRIVATE_KEY
        value: ""
